spring:
  data:
#    redis:
#      port: 26379
#      password:
#      sentinel:
#        master: mymaster
#        nodes: localhost
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 300000
#  kafka:
#    bootstrap-servers: localhost:8697
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hs_dzbb?currentSchema=user_service
    username: hp
    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K
  jpa:
    hibernate:
      ddl-auto: none  # or create-drop if you want to recreate tables on each application startup
    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: none  # or create-drop if you want to recreate tables on each application startup
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
#    url: jdbc:postgresql://postgres:5432/hs_dzbb?currentSchema=user_service
#
#    user: hp
#    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K

server:
  port: 8080


cors:
  allowed-origin: http://localhost:8080

#springdoc:
#  swagger-ui:
#    path: /user/swagger-ui.html
